<?php

namespace craftpulse\herald\mcp;

use Carbon\Carbon;
use DateTimeInterface;

/**
 * =========================================================================
 * HTTP-transport session value object.
 *
 * Represents one logical MCP session, identified by the opaque token
 * returned in the `Mcp-Session-Id` response header on `initialize` and
 * required on every subsequent POST. Sessions are persisted to Craft's
 * PSR-16 cache by `Sessions` service — see that class for the storage
 * contract.
 *
 * Field semantics:
 *
 *   - `id` — cryptographically random opaque string, generated by
 *     `Sessions::create()` via `random_bytes(16)`. Never derived from
 *     user-controlled input.
 *   - `createdAt` — set once at `create()` time, stable for the
 *     session's lifetime.
 *   - `lastSeenAt` — bumped by `Sessions::touch()` on every authenticated
 *     POST. Drives the sliding-TTL eviction policy.
 *   - `protocolVersion` — captured from the `initialize` handshake's
 *     `protocolVersion` param. Locked to the MCP wire pin (currently
 *     `2025-06-18`).
 *   - `clientName` — from `clientInfo.name`. Threaded into the audit
 *     log via `InvocationContext::$clientName`.
 *   - `userId` — Craft user id when the bearer/OAuth layer (sub-gate
 *     7.2) authenticates the session. Null in 7.1 (no auth yet).
 *
 * Serialisation round-trips through `toArray()` / `fromArray()` so the
 * cache stays a plain JSON-friendly blob (no PHP-class headers in the
 * cache, no PSR-16-backend gotchas around `__sleep` / `__wakeup`).
 * =========================================================================
 *
 * @author Craftpulse
 * @since  5.0.0
 */
final class Session
{
    // Public Methods
    // =========================================================================

    /**
     * @param string             $id              Opaque session id.
     *                                            Generated by
     *                                            `Sessions::create()`.
     * @param DateTimeInterface  $createdAt       Creation timestamp.
     * @param DateTimeInterface  $lastSeenAt      Most-recent activity
     *                                            timestamp. Initially
     *                                            equal to `createdAt`.
     * @param string             $protocolVersion MCP protocol version
     *                                            from the `initialize`
     *                                            handshake.
     * @param string|null        $clientName      `clientInfo.name` from
     *                                            initialize, or null
     *                                            when the client omits
     *                                            it.
     * @param int|null           $userId          Craft user id once
     *                                            auth resolves (sub-
     *                                            gate 7.2). Always null
     *                                            in 7.1.
     *
     * @author Craftpulse
     * @since  5.0.0
     */
    public function __construct(
        public readonly string $id,
        public readonly DateTimeInterface $createdAt,
        public DateTimeInterface $lastSeenAt,
        public readonly string $protocolVersion,
        public readonly ?string $clientName = null,
        public ?int $userId = null,
    ) {
    }

    /**
     * Reconstruct from a cache-fetched array. Inverse of `toArray()`.
     *
     * @param array<string,mixed> $row
     *
     * @author Craftpulse
     * @since  5.0.0
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (string) $row['id'],
            createdAt: Carbon::parse((string) $row['createdAt']),
            lastSeenAt: Carbon::parse((string) $row['lastSeenAt']),
            protocolVersion: (string) $row['protocolVersion'],
            clientName: isset($row['clientName']) && is_string($row['clientName']) && $row['clientName'] !== ''
                ? $row['clientName']
                : null,
            userId: isset($row['userId']) && is_int($row['userId']) ? $row['userId'] : null,
        );
    }

    /**
     * Serialise to a plain associative array suitable for cache storage.
     * Stable wire shape — added fields land at the end so existing
     * cached blobs round-trip cleanly.
     *
     * @return array<string,mixed>
     *
     * @author Craftpulse
     * @since  5.0.0
     */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'createdAt' => $this->createdAt->format(DATE_ATOM),
            'lastSeenAt' => $this->lastSeenAt->format(DATE_ATOM),
            'protocolVersion' => $this->protocolVersion,
            'clientName' => $this->clientName,
            'userId' => $this->userId,
        ];
    }
}
